-- coleccion diplomados --

INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3911,'C.DPI&808.887&M394l','Leer y escribir el Minimun vital','Masferrer, Alberto','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3912,'C.DPI&863&E77t','Trenes','Espino, Miguel Angel','1997','Dirección de publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3913,'C.DPI&862&E74d','El Desencanto','Escudos, Jacinta','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3914,'C.DPI&863&L747c','El Canto a un Cantado','Lindo, Ricardo','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3915,'C.DPI&823&J27l','La Vuelta de Tuerca','James, Henry','1999','Dirección General de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3917,'C.DPI&843&B532T','Tristán e Isolda','Béroul, y Thomas','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3918,'C.DPI&808.838&K47l','Lujuria Tropical','Masferrer, Alberto','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3919,'C.DPI&863&R456c','El Cojo Bueno','Rey Rosa, Rodrigo','2001','Dirección General de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3920,'C.DPI&282&C828d','Descripción geográfico-moral de la Diócesis de Goathemala : (parroquias correspondientes al actual territorio salvadoreño)','Cotéz y Larraz, Pedro','2000','Dirección General de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3921,'C.DPI&861&G576e','Esta Mueca Circular y Sola','Góchez Sosa, Rafael','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3922,'C.DPI&860.1&R294P','Popol Vuh','Recinos, Adrian','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3923,'C.DPI&861&G345l','La Mágica Raíz','Geoffroy Rivas, Pedro','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3924,'C.DPI&972.84&E77l','Los Símbolos Patrios','Espinosa, Francisco','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3925,'C.DPI&861&A729c','Cuando se Enciendan las Lamparas','Armijo, Roberto','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3927,'C.DPI&808.831&S159c','Cuentos de Barro.','Salazar Arrué, Salvador','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3928,'C.DPI&808.82&M394e','El Dinero Maldito','Masferrer, Alberto','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3929,'C.DPI&808.82&P748m','Mar Adentro','Pohl, Carlos','1989','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3930,'C.DPI&861&E74c','Cantos a la Noche','Escobar Galindo, David','1990','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3931,'C.DPI&861&S211e','El Venado y el Colibrí','Sancho, Eduardo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3932,'C.DPI&861&H565c','Escritores de la Paz','Herrera, Antonio Alfredo','1995','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3933,'C.DPI&861&M376m','Media Luz','Martell Ccaminos, Ricardo','1980','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3934,'C.DPI&861&E24c','Celebración de la Rosa','Elías, Rolando','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3936,'C,DPI&809.933&R696e','El Infierno','Rodríguez, Guillermo','1979','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3937,'C.DPI&861&E28p','Piel de Ojos','Eguizábal, Daniel','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3938,'C.DPI&861&A316l','Luna de Basalto','Alas, Javier','1995','Dirección de Publicacione e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3939,'C.DPI&808.82&G283o','Obras Completas','Gavidia, Francisco','1976','Dirección de Publicaciones e Impresiones');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3940,'C.DPI&863&L431','Lazarillo de Tormes',NULL,'1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3941,'C.DPI&861&E77j','Jícaras Tristes','Espino, Alfredo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3942,'C.DPI&861&S481m','Meridiano de Orquídea y Niebla','Serpas Gutiérrez, Lilian','1982','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3943,'C.DPI&301&L318s','Salvadoreños en Calgary el Proceso de Configuración de un Nuevo Grupo Etnico','Lara Martínez, Carlos Benjamín','1994','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3944,'C.DPI&511.3&M828t','Teoría del Número','Morales M., Rodolfo','1977','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3945,'C.DPI&809.923&E74h','Hispanoamericana en la Ruta de su Identidad, encuentro de dos Mundos','Escamilla, Manuel Luis','1994','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3946,'C.DPI&808.831&G576d','Desnudos en una Capilla','Góchez, Rafael Francisco','1993','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3947,'C.DPI&900&L813e','Estudio histórico de la evolución política de la humanidad','Lara Velado, Roberto','1973','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3948,'C.DPI&808.838&C355l','Libro de los Descaríos','Castro, Carlos','1996','Dirección de Publicaciones e Impresps');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3949,'C.DPI&863&O66t','Te Recuerdo que Moriremos algún día','Orellana, Mauricio','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3950,'C.DPI&813&E74c','Cuentos Sucios','Escudos, Jacinta','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3951,'C.DPI&860&M894p','Páginas Colombianas','Mosquera Irurita, Tito','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3952,'C.DPI&928&M533','Memoria del General Manuel José Arce',NULL,'1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3953,'C.DPI&861&A283t','De Tiempos y Hombres','Aguilar Avilés, Gilberto','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3954,'C.DPI&374.012&E74u','Una Educación entre dos Imperios y la Educación de Adultos.','Escamilla Manuel Luis','1990','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3955,'C.DPI&512.9&C212a','Algebra Elemental','Cañas Villegas, Helio Neftalí','1991','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3956,'C.DPI&930.1&A565a','La Arqueología de Quelepa','Andrews V., E. Wyllys','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3957,'C.DPI&574&B715b','Biología','Bonilla Marroquín, Luis A.','1995','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3958,'C.DPI&581&L177c','Compendio de Botánica Sistmática','Lagos, Jorge Adalberto','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3959,'C.DPI&574.192&B562b','Bioquímica y Fundamentos de Química Orgánica','Betancourt, Herbert','1984','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3960,'C.DPI&972.84&L321e','El Salvador, descubrimiento, conquista y colonización','Larde y Larin, Jorge','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3961,'C.DPI&972.84&L31e','El Salvador: historia de sus pueblos, villas y ciudades','Lardé y Larín, Jorge','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3961,'C.DPI&972.84&L31e','El Salvador: historia de sus pueblos, villas y ciudades','Lardé y Larín, Jorge','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3962,'C.DPI&863&S161n','Narrativa Completa de Salarré','Salazar Arrué, Salvador','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3962,'C.DPI&863&S161n','Narrativa Completa de Salarré','Salazar Arrué, Salvador','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3962,'C.DPI&863&S161n','Narrativa Completa de Salarré','Salazar Arrué, Salvador','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3963,'C.DPI&325.3&E74t','Los Tlaxcaltecas en Centro América','Escalante Arce, Pedro Antonio','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3964,'C.DPI&411&P438e','Escribamos Bien','Pérez Mejía, Ladislao','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3965,'C.DPI&972.84&B234m','Monografías departamentales','Barbera, Santiago I','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3966,'C.DPI&923.2&D352m','José Matías Deldago, Prócer Centroamericano','Meléndez Chaverri, Carlos','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3967,'972.84&M361a','Apreciación Sociológica de la Independencia Salvadoreña','Marroquin, Alejandro Dagoberto','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3968,'C.DPI&861&H766l','La Odisea','Homero','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3969,'C.DPI&862&H766l','La Iliada','Homero','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3970,'C.DPI&840.4&C997o','El Otro Mundo: Historia Cómica de los Estados e Imperios del Sol','Cyrano de Bergerac, Siviniano','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3971,'C.DPI&808.81&A316p','Piedras en el Hucacán','Alas, Javier','1993','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3972,'C.DPI&972.84&B885e','El Salvador, la tierra y el hombre','Browning, David','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3973,'C.DPI&861&G934p','Poesía Reunida','Gerra Trigueros, Alberto','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3974,'C.DPI&972.84&B265r','Reseña Histórica de la Villa de San Salvador','Barón Castro, Rodolfo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3974,'C.DPI&972.84&B265r','Reseña Histórica de la Villa de San Salvador','Barón Castro, Rodolfo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3974,'C.DPI&972.84&B265r','Reseña Histórica de la Villa de San Salvador','Barón Castro, Rodolfo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3975,'C.DPI&972.843 32&A479h','Historia de Cacaopera','Amaya Amaya, Miguel Angel','1985','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3976,'C.DPI&861&K46c','Es Cara Musa','Kijadurias, Alfonso','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3977,'C.DPI&808.81&L742l','Los Infiernos Esplendidos','Lindo, Roger','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3978,'C.DPI&808.81&A366u','Umbrales','Alegría, Claribel','1997','Dirección de Publicaciones de Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3979,'C.DPI&808.81&E74s','Solamente Una Vez','Escobar, Francisco Andrés','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3980,'C.DPI&863&M542t','Tres Novelas','Menen Desleal, Alvaro','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3981,'C.DPI&861&A325f','Fuego Brujo','Alba, María de','1978','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3982,'C.DPI&863.3&C429c','El Coloqui de los Perros y otras Novelas Ejemplares','Cervantes Saavedra, Miguel de','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3983,'C.DPI&863&M534l','Los Héroes Tienen Sueño','Menjivar Ochoa, Rafael','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3984,'C.DPI&860&A495e','El Libro dle Trópico','Ambrogi, Arturo','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3985,'C.DPI&861&D136l','La ventana en el rostro','Daltón, Roque','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3986,'C.DPI&808.831&L742a','Aquí se Cuentan Cuentos','Lindo, Hugo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3987,'C.DPI&861&G343l','Los Nietos del Jaguar','Geoffroy Rivas, Pedro','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3988,'C.DPI&863.44&E77m','Mitología de Cuscatlán/Como cantan Allá','Espino, Miguel Angel','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3989,'C.DPI&861&S159o','O-Yarkandal','Salazar Arrué, Salvador','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3990,'C.DPI&868.992 2&L318l','La Casa de Vidrio','Lars, Claudia','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3991,'C.DPI&860.1&A495c','Crónicas','Ambrogi, Arturo','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3992,'C.DPI&864.4&M394e','Ensayos','Masferrer, Alberto','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3993,'C.DPI&808.831&G283c','Cuentos y Narraciones','Gavidia, Francisco','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3994,'C.DPI&398.24&S579f','Fábulas','Siguenza, León','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3996,'C.DPI&863&M542i','La Ilustre Familia Androide','Menen Desleal, Alvaro','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3997,'C.DPI&863&A366c','Cenizas de Izalco','Alegria, Claribel','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3998,'C.DPI&868.992 2&E74t','Tierra Azul donde el Venado Cruza','Escobar Velado, Oswaldo','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (3999,'C.DPI&861&R788e','El Bosque de Apolo y Otros Poemas','Rosales y Rosales, Vicente','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4000,'C.DPI&863&M537l','Las Mormonas y Otros Cuentos','Méndez, José María','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4001,'C.DPI&861&Q6c','Corasón con S','Quiteño, Serafín','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4002,'C.DPI&861.44&C846c','Cantos de la Tierra Promedida','Cotto, Juan','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4003,'C.DPI&863&R616a','Andanzas y Malandanzas','Rivas Bonilla, Alberto','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4004,'C.DPI&860.9&P426l','La Muerte de la Tortola','Peralta Lagos, José María','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4005,'C.DPI&863.44&L747a','Arca de los Olvidos','Lindo, Ricardo','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4006,'C.DPI&861.44&E74p','Pasión del Tiempo','Escobar Galindo, David','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4008,'C.DPI&863.44&C387t','Todo el Códice','Cea, José Roberto','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4009,'C,DPI&863.44&A694u','Un Día en la Vida','Argueta, Manlio','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4010,'C.DPI&861.4&P864c','Ciego Afán','López Vallecillos, Italo','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4011,'C.DPI&864.44&L864e','Ensayos Literarios','López, Matilde Elena','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4012,'C.DPI&864.4&G934p','Poesía Versus Arte','Guerra Trigueros, Alberto','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4013,'C.DPI&861.44&C764v','Versos de Ayer','Contreras, Raúl','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4014,'C.DPI&862&M542l','Luz Negra','Menen Desleal, Alvaro','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4015,'C.DPI&823&M531c','Cuentos de la Veranda','Melville, Hernan','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4016,'C.DPI&863&S957m','Memorias de Oppéde','Súsnsin, Consuelo','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4017,'C.DPI&808.887&S713e','El Escrito de la Defensa y Otros Folios','Sorto Cambell, José Enríque','1996','Dirección de Publicación e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4018,'C.DPI&809.916&B228e','El Terremoto de San Salvador','Barba Jacob, Porfirio','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4019,'C.DPI&972.728 412 5&C436','Chalchuapa',NULL,'1985','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4020,'C.DPI&460&R616l','La Lengua Salvadoreña El Español que Hablamos en El Salvador','Rivas, Pedro Geoffroy','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4021,'C.DPI&907&M779e','Etnohistoria de El Salvador','Montes Mozo, Santiago','1977','Dirección  de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4022,'C.DPI&861&CH538e','El Libro de las Respuestas','Chinchilla, Miguel Angel','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4024,'C.DPI&808.83&L742j','Justicia Señor Gobernador','Lindo, Hugo','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4025,'C.DPI&809&G166t','Tiro Al Blanco','Gallegos Valdés, Luis','1978','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4026,'C.DPI&863&M542l','La Bicicleta al Pie de la Muralla','Menen Desleal, Alvaro','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4027,'C.DPI&862&V437s','San Salvador Después del Eclipse','Velis, Carlos','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4028,'C.DPI&808.82&S527s','Sueño de Noche de Verano','Shakespeare, William','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4029,'C.DPI&862&Ch512e','El Sombrero de Otoño','Chávez Velásco, Waldo','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4030,'C.DPI&861&E77t','Tren','Espino, Alfredo Ernesto','1993','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4031,'C.DPI&808.83&M394v','Una Vida en el Cine','Masferrer, Alberto','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4033,'C.DPI&801.953&G283','Francisco Gavidia Antología de su Narrativa',NULL,'1986','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4034,'C.DPI&809.8&C212d','Diccionario Escolar de Autores Salvadoreños','Cañas Dinarte, Carlos','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4035,'C.DPI&972.84&E49h','Historia de El Salvador','Ministerio de Educación (El Salvador)','1994','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4035,'C.DPI&972.84&E49h','Historia de El Salvador','Ministerio de Educación (El Salvador)','1994','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4036,'C.DPI&808.803 75&H565m','Mentiras y Verdades','Herrera Velado, Francisco','1977','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4037,'C.DPI&972.84&C348a','Antecedentes Históricos de la Guerra Civil','Castellanos, Juan Mario','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4039,'C.DPI&972.84&L864i','San Salvador en la Conexión Centroamericana al Imperio del Septentrión','López, Eugenia','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4040,'C.DPI&929.9&E77s','Simbolos Patrios de las Naciones de Centroamérica','Espinosa, Francisco','2001','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4041,'C.DPI&848&E42c','Crónica de Alemania','Elías, Rolando','1983','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4042,'C.DPI&861&L864a','Alicia en la Cárcel de las Maravillas','López Lomas, Estela Alicia','1994','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4044,'C.DPI&864&L318t','Tormenta entre las Manos','Lara Martínez, Rafael','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4045,'C.DPI&861.4&L334p','Poesía Completa','Lars, Claudia','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4046,'C.DPI&793.3&A769d','Danzas Folkloricas en la Villa de los Santos','Arosemena Morena, Julio','1977','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4047,'C.DPI&972.728 423 6&D418r','Reliquia','Deodanes, Sabino','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4048,'C.DPI&741.5&G166c','Caricaturas Verbales','Gallegos Valdés, Luis','1997','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4050,'C.DPI&908&H673','Historia sagrada e historia profana: el sentido de la historia salvadoreña en la obra de Francisco Gavidia.','Lara Martínez, Rafael','1991','CONCULTURA');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4051,'C.DPI&782.253&F363r','Radiografía del Dolor','Fernández, Julio Fausto','1974','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4052,'C.DPI&860&E74e','El Arbol de Todos','Escobar Galindo, David','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4053,'C.DPI&155.423&P227q','Quiero Aprender','Paredes Sánchez, Leopoldo','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4054,'C.DPI&519.3&O77t','Trazos Geométricos','Ortez, José César','1990','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4055,'C.DPI&070.44&G151e','La Espuma de los Sueños','Galeas, Geovani','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4056,'C.DPI&750.1&C813s','La pintura en El Salvador','Cornejo, Jorge A.','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4056,'C.DPI&750.1&C813s','La pintura en El Salvador','Cornejo, Jorge A.','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4057,'C.DPI&864&A729a','Aventura Hacia el País Perdido','Armijo, Roberto','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4058,'C.DPI&861&S237c','La Casa en Marcha','Santos, Carlos','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4059,'C.DPI&863.3&Q5v','La Vida del Buscón Llamado don Pablos','Quevedo, Francisco','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4060,'C.DPI&070&V665','Obras Escogidas','Viera Altamirano, Napoleón','1998','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4061,'C.DPI&861.44&A316l','Luciférnagas','Alas, Javier','1993','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4062,'C.DPI&861&A325','Alba de Otro Milenio',NULL,'2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4063,'C.DPI&808.82&C764o','Obra Poética','Contreras, Raúl','1996','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4064,'C.DPI&861.4&L334p','Poesía Completa','Lars, Claudia','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4065,'C.DPI&069.09&M986','Museo Nacional David J. Guzmán',NULL,'1986','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4118,'C.DPI&861&A336s','Saudade','Alegría, Claribel','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4119,'C.DPI&862&Ch539n','Nuevo Teatro Salvadoreño','Chinchilla, Miguel Angel','1997','Dirección de Publicaciones e impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (4129,'C.DPI&925.8&G993c','Obras Escogidas','Guzmán, David J.','2000','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (5022,'C.DPI&972.84&D289s','Suchitoto','Burgos, Hugo de','1999','Dirección de Publicaciones e Impresos');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (5337,'DIP&658.568&C949c&1999','La calidad no cuesta: el arte de cerciorarse de la calidad','Crosby, Philip B.','1999','CECSA');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6753,'DIP&658.51&H224r','Reingeniería: Olvide lo que usted sabe sobre cómo debe funcionar una empresa.','Hammer, Michael','1994','Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6753,'DIP&658.51&H224r','Reingeniería: Olvide lo que usted sabe sobre cómo debe funcionar una empresa.','Hammer, Michael','1994','Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6753,'DIP&658.51&H224r','Reingeniería: Olvide lo que usted sabe sobre cómo debe funcionar una empresa.','Hammer, Michael','1994','Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6753,'DIP&658.51&H224r','Reingeniería: Olvide lo que usted sabe sobre cómo debe funcionar una empresa.','Hammer, Michael','1994','Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6754,'DIP&658.51&J65r','Reingeniería de procesos de negocios','Johansson, Henry J.','1996','Limusa Noriega Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6754,'DIP&658.51&J65r','Reingeniería de procesos de negocios','Johansson, Henry J.','1996','Limusa Noriega Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6754,'DIP&658.51&J65r','Reingeniería de procesos de negocios','Johansson, Henry J.','1996','Limusa Noriega Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6754,'DIP&658.51&J65r','Reingeniería de procesos de negocios','Johansson, Henry J.','1996','Limusa Noriega Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6755,'DIP&658.51&L913r','Reingeniería de la organización: Enfoque sistemático para la revitalización corporativa','Lowenthal, Jeffrey N.','1997','Panorama Editorial');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6755,'DIP&658.51&L913r','Reingeniería de la organización: Enfoque sistemático para la revitalización corporativa','Lowenthal, Jeffrey N.','1997','Panorama Editorial');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6756,'DIP&658.51&M277c','Cómo hacer reingeniería','Manganelli, Raymond L.','1995','Grupo Editorial Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6756,'DIP&658.51&M277c','Cómo hacer reingeniería','Manganelli, Raymond L.','1995','Grupo Editorial Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6757,'DIP&658.114&D124t','Teoría y diseño organizacional','Daft, Richard I.','2000','International Thomson Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6758,'DIP&658.568&M667p','El proceso estratégico: Conceptos y casos','Mintzberg, Henry','1997','Prentice Hall');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6759,'DIP&658.562&T112g','Guía para implementar la norma ISO 9000 para empresas de todos tipos y tamaños','Tabla Guevara, Guillermo','1998','Prentice Hall');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6760,'DIP&658.562&R843i','ISO 9000','Rothery, Brian','1993','Panorama editorial');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6761,'DIP&657.458&V697a','La auditoría de los sistemas de gestión de la calidad','Vilar Barrio, José Francisco','1999','Fundación confemetal');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6762,'DIP&658.568&I799q','¿Que es el control de calidad? la modalidad japonesa','Ishikawa, Kaoru','1988','Grupo Editorial Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6763,'DIP&658.562&C266i','Implementación de ISO 14001 una versión macroscópica','Cárdenas, Leonardo J.','1999','Ediciones Castillo');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6764,'DIP&658.51&M875r','Reingeniería: Cómo aplicarla con éxito en los negocios','Morris, Daniel','1995','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6764,'DIP&658.51&M875r','Reingeniería: Cómo aplicarla con éxito en los negocios','Morris, Daniel','1995','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6764,'DIP&658.51&M875r','Reingeniería: Cómo aplicarla con éxito en los negocios','Morris, Daniel','1995','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6764,'DIP&658.51&M875r','Reingeniería: Cómo aplicarla con éxito en los negocios','Morris, Daniel','1995','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6765,'DIP&658.404&G738a','Administración de proyectos exitosos','Grahan, Robert J.','1999','Prentice-Hall');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6766,'DIP&658.16&W238c','Cómo administrar con el método deming','Walton, Mary','1988','Grupo Editorial Norma');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6767,'DIP&658.51&G492d','Dirección por servicio: La otra calidad la única reingeniería','Ginebra, Joan','1999','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6768,'DIP&658.568&C949c','Calidad sin lagrimas: El arte de administrar sin problemas','Crosby, Philip B.','1999','Continental, S.A. de C.V.');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6769,'DIP&658.568&V697c','Cómo implementar y gestionar la calidad total','Vilar Barrio, José Francisco','S/F','Fundación CONFEMETAL');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6770,'DIP&658.568&V697n','Las 7 nuevas herramientas para la mejora de la calidad','Vilar Barrio, José Francisco','S/F','Fundación CONFEMETAL');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6771,'DIP&658.16&S822p','Planeación estratégica: lo que todo director debe saber','Steiner, George A.','2000','Continental, S.A. de C.V.');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6772,'DIP&658.404&G453a','Administración éxitosa de proyectos','Gido, Jack','1999','International Thomson Editores');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6773,'DIP&658.04&F831o','Organización de empresas: análisis, diseño y estructura','Fincowsky, Enrique Benjamín Franklin','1999','McGraw-Hill');
INSERT INTO libro(mfn,clasificacion,nombre,autor,fechaPublicacion,idEditorial) VALUES (6774,'DIP&658.51&V697a','Cómo mejorar los procesos en su empresa: el control estadístico de procesos (SPC), herramienta fundamental en el incremento de la competitividad','Vilar Barrio, José Francisco','1999','Fundación CONFEMETAL');


INSERT INTO inventario(numeroInventario,idLibro) VALUES (5793,25864);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5792,25865);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5764,25866);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5745,25867);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5735,25868);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5702,25869);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5740,25870);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5713,25871);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5758,25872);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5798,25873);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5810,25874);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5814,25875);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5816,25876);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5809,25877);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5797,25878);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5796,25879);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5795,25880);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5834,25881);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5779,25882);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5778,25883);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5786,25884);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5774,25885);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5826,25886);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5772,25887);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5784,25888);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5833,25889);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5782,25890);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5725,25891);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5811,25892);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5817,25893);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5813,25894);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5812,25895);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5822,25896);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5825,25897);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5835,25898);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5800,25899);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5805,25900);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5802,25901);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5806,25902);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5807,25903);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5803,25904);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5801,25905);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5808,25906);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5692,25907);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5695,25908);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5694,25909);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5757,25910);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5756,25911);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (8078,25912);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5831,25913);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5770,25914);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5748,25915);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5750,25916);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5777,25917);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5752,25918);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5751,25919);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5754,25920);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5739,25921);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5738,25922);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5699,25923);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5697,25924);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5693,25925);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5775,25926);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5776,25927);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (7745,25928);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (8968,25929);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5696,25930);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5723,25931);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5760,25932);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5759,25933);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5762,25934);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5783,25935);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5789,25936);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5787,25937);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5781,25938);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5790,25939);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5721,25940);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5718,25941);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5734,25942);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5726,25943);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5736,25944);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5700,25945);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5716,25946);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5719,25947);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5715,25948);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5708,25949);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5729,25950);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5728,25951);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5720,25952);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5722,25953);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5732,25954);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5727,25955);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5733,25956);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5717,25957);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5724,25958);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5705,25959);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5707,25960);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5704,25961);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5714,25962);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5711,25963);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5712,25964);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5710,25965);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5709,25966);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5737,25967);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5788,25968);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5744,25969);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5743,25970);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5742,25971);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5818,25972);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5804,25973);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5819,25974);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5731,25975);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5698,25976);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5771,25977);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5791,25978);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5794,25979);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5769,25980);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5765,25981);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5768,25982);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5741,25983);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5766,25984);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5763,25985);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5690,25986);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5691,25987);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5761,25988);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5749,25989);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5747,25990);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5746,25991);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5848,25992);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5847,25993);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5849,25994);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5850,25995);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5827,25996);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5828,25997);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5820,25998);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5823,25999);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5832,26000);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5821,26001);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5824,26002);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5815,26003);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5856,26004);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5855,26005);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (842,26006);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5858,26007);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5852,26008);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5854,26009);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5851,26010);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5853,26011);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5860,26012);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5861,26013);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5859,26014);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5829,26015);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5785,26016);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5780,26017);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (5857,26018);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (7019,26019);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6059,26020);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6041,26021);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6042,26022);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6043,26023);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6044,26024);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6045,26025);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6046,26026);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6047,26027);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6048,26028);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6049,26029);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6050,26030);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6051,26031);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6052,26032);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6053,26033);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6054,26034);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6055,26035);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6056,26036);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6057,26037);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6058,26038);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6061,26039);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6062,26040);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6063,26041);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6064,26042);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6065,26043);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6066,26044);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6067,26045);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6068,26046);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6069,26047);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6070,26048);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6071,26049);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6072,26050);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6073,26051);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6074,26052);
INSERT INTO inventario(numeroInventario,idLibro) VALUES (6075,26053);
